"""
Data models for AI analysis operations.
Extracted from ai_analysis_coordinator.py to improve separation of concerns.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Optional, Any, Union


@dataclass
class AnalysisRequest:
    """Request for AI analysis."""
    request_type: str  # 'similarity', 'classification', 'intent_analysis'
    content: Union[str, List[str]]
    context: Optional[Dict[str, Any]] = None
    timeout: Optional[float] = None  # Use LLM-Providers default
    temperature: float = 0.1


@dataclass
class ClassificationRule:
    """A classification rule generated by LLM."""
    pattern: str
    category: str
    reasoning: str
    created_at: datetime
    success_count: int = 0
    failure_count: int = 0


@dataclass 
class AnalysisResponse:
    """Response from AI analysis."""
    success: bool
    result: Any
    confidence: float
    reasoning: str
    metadata: Dict[str, Any]
    processing_time: float